spring:
  application:
    name: ${vcap.application.application_name:application}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-edwin.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

wfd:
  appetizer:
    order: 1
    type: appetizer
    menu:
      - Hummus
      - Crab Cakes
      - Mozzerella Sticks
  entree:
    order: 2
    type: dinner
    menu:
      - Steak
      - Chicken
      - Fish
  dessert:
    order: 3
    type: dessert
    menu:
      - Chocolate Cake
      - Banoffee
      - Ice Cream
