version: '2'
services:
  eureka:
   #build: ../refarch-cloudnative-netflix-eureka/docker
   image: netflix-eureka
   ports:
    - "8761:8761"

  config:
   #build: ../refarch-cloudnative-spring-config/docker
   image: spring-config
   links:
    - eureka
   ports:
    - "8888:8888"
   env_file:
    - wfd.env

  zuul:
   #build: ../refarch-cloudnative-netflix-zuul/docker
   image: netflix-zuul
   links:
    - eureka
   ports:
    - "80:8080"
   env_file:
    - wfd.env

  ui:
   #build: ../refarch-cloudnative-wfd-ui/docker
   image: wfd-ui
   links:
    - eureka
    - config
   ports:
    - "8181:8181"
   env_file:
    - wfd.env

  menu:
   #build: ../refarch-cloudnative-wfd-menu/docker
   image: wfd-menu
   links:
    - eureka
    - config
   ports:
    - "8180:8180"
   env_file:
    - wfd.env

  appetizer:
   #build: ../refarch-cloudnative-wfd-appetizer/docker
   image: wfd-appetizer
   ports:
    - "8082:8082"
   links:
    - eureka
    - config
   env_file:
    - wfd.env

  entree:
   #build: ../refarch-cloudnative-wfd-entree/docker
   image: wfd-entree
   links:
    - eureka
    - config
   ports:
    - "8081:8081"
   env_file:
    - wfd.env

  dessert:
   #build: ../refarch-cloudnative-wfd-dessert/docker
   image: wfd-dessert
   links:
    - eureka
    - config
   ports:
    - "8083:8083"
   env_file:
    - wfd.env
